nickname = "Lalla"
str = 17
dex = 9
con = 17
int = 9
wis = 11
cha = 16
bab = 0
ac = 12
hp = 6
hd = 0
weapondie = 12
initiative = 13
level = 1
class = "Rogue"
armor = "Leather Armor"
weapon = "greataxe"
area = "City"
room = "Inn"
position = "59"
previousRoom = "Inn"
previousArea = "City"
