nickname = "Lolos"
str = 16
dex = 18
con = 8
int = 13
wis = 13
cha = 12
bab = 0
ac = 18
hp = 6
hd = 0
weapondie = 6
initiative = 22
level = 1
class = "Rogue"
armor = "Scale Mail"
weapon = "short sword"
area = "City"
room = "Inn"
position = "30"
previousRoom = "Inn"
previousArea = "City"
