nickname = "MIkee"
str = 10
dex = 9
con = 11
int = 10
wis = 9
cha = 13
bab = 0
ac = 14
hp = 6
hd = 0
weapondie = 3
initiative = 5
level = 1
class = "Rogue"
armor = "Chain Shirt"
weapon = "fist"
area = "City"
room = "Inn"
position = "6"
previousRoom = "Inn"
previousArea = "City"
